### ISSUE TITLE
security vulnerability in minimatch

### ISSUE THREAD

**Issue by bcoe** [bmeck/dotignore#4]
I'd love to use this library in `standard-version` to parse the `.gitignore`, but it looks like minimatch has a security vulnerability.

```bash
 deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

If you don't get to it first, I'll submit a patch ASAP.

**Comment by ljharb** [comment]
v0.1.2 has been published which includes this update.
