### ISSUE TITLE
Default value for delimiter is not Windows-friendly

### ISSUE THREAD

**Issue by nexdrew** [bmeck/dotignore#6]
See https://github.com/conventional-changelog/standard-version/pull/230#issuecomment-353496177

In order to use this library in a Windows-friendly way, you have to change the default `delimiter` value. Seems like it would be better to default to `require('path').sep` instead, so that matching against os-specific paths would work cross-platform out of the box.

**Comment by ljharb** [comment]
Seems reasonable. Want to submit a PR?
